1089IbnCimad.Shadharat.DM1986ARN01-ara1:
  fullreference: "Ibn al-ʿImād al-Ḥanbalī. <i>Šaḏarāt al-ḏahab</i>. Ed. Maḥmūd al-Arnaʾūṭ. 1st Ed. Dimašq-Bayrūt: Dār Ibn Kaṯīr, 1406/1986"
  bookURI: /1089IbnCimad/Shadharat/DM1986ARN01-ara1/
0748Dhahabi.TarikhIslam.BY1990TAD01-ara1:
  fullreference: "al-Ḏahabī. <i>Taʾrīḫ al-islām</i>. Ed. ʿUmar ʿAbd al-Salām Tadmuri. 1st Ed. Bayrūt: Dār al-Kitāb al-ʿArabī, 1410/1990"
  bookURI: /0748Dhahabi/TarikhIslam/BY1990TAD01-ara1/
0748Dhahabi.TarikhIslam.BY2003BCM01-ara1:
  fullreference: "al-Ḏahabī. <i>Taʾrīḫ al-islām</i>. Ed. Baššār ʿAwād Maʿrūf. 1st Ed. Bayrūt: Dār al-Ġarb al-Islāmī, 1424/2003"
  bookURI: /0748Dhahabi/TarikhIslam/BY2003BCM01-ara1/
0230IbnSacd.TabaqatKubra.BY1990MQC01-ara1:
  fullreference: "Ibn Saʿd. <i>al-Ṭabaqāt al-kubrá</i>. Ed. Muḥammad ʿAbd al-Qādir ʿAṭā. 1st ed. Bayrūt: Dār al-kutub al-ʿilmīyaŧ, 1410/1990"
  bookIRU: /0230IbnSacd/TabaqatKubra/BY1990MQC01-ara1/